# -*- coding: utf-8 -*-
"""DIVA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qnMiPt-Tz9xWDV_E-ueR9Pe5jvkqPYe
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/covid_epidemiology.csv')

print
df.head()

df.shape